language: python
cache: pip
python:
    - 2.7
    - 3.6
    #- nightly
    #- pypy
    #- pypy3
matrix:
    allow_failures:
        - python: nightly
        - python: pypy
        - python: pypy3
env:
  - LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
install:
    - pip install -r requirements.txt
    - pip install flake8 gym pillow six
    - git clone https://github.com/sbrodeur/evert
    - pushd evert # change into Evert dir for compilation
    - sudo apt-get install mesa-common-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libgl1-mesa-dev
    - sudo apt-get install swig
    - aclocal && autoconf && libtoolize && automake --add-missing
    - ./configure CFLAGS='-g -O0' CXXFLAGS='-g -O0'
    - make && sudo make install
    - pushd python # this will not work for random reasons
    - swig -python -c++ -I../include -o evert_wrap.cpp evert.i
    - sudo pip2 install -e .
    - sudo pip3 install -e .
    - popd # change out of Python bindings dir
    - popd # change out of Evert dir
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    # pytest --capture=sys  # add other tests here
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - cd tests
    - ./run_tests.sh
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
